image: alpine:latest

stages:
  - test
  - deploy

test:
  image: node:12-alpine
  stage: test
  tags:
    - docker
  only:
  - master
  - merge_requests
  script:
    - npm install
    - npm run lint:js
    - npm run lint:styles

pages:
  stage: deploy
  script:
  - apk add --no-cache rsync
  - rsync -a --exclude=public/ ./ ./public/
  artifacts:
    paths:
    - public
  tags:
    - docker
  only:
    - master
